//clubs used as guessing options 

const soccer_clubs = [
    {'label': 'Paris Saint-Germain', 'value': 'Paris Saint-Germain', 'logo': 'https://cdn.sofifa.net/teams/73/60.png'},
  {'label': 'FC Barcelona', 'value': 'FC Barcelona', 'logo': 'https://cdn.sofifa.net/teams/241/60.png'},
  {'label': 'FC Bayern München', 'value': 'FC Bayern München', 'logo': 'https://cdn.sofifa.net/teams/21/60.png'},
  {'label': 'Manchester United', 'value': 'Manchester United', 'logo': 'https://cdn.sofifa.net/teams/11/60.png'},
  {'label': 'Juventus', 'value': 'Juventus', 'logo': 'https://cdn.sofifa.net/teams/45/60.png'},
  {'label': 'Real Madrid CF', 'value': 'Real Madrid CF', 'logo': 'https://cdn.sofifa.net/teams/243/60.png'},
  {'label': 'Manchester City', 'value': 'Manchester City', 'logo': 'https://cdn.sofifa.net/teams/10/60.png'},
  {'label': 'VfL Wolfsburg', 'value': 'VfL Wolfsburg', 'logo': 'https://cdn.sofifa.net/teams/175/60.png'},
  {'label': 'Atlético de Madrid', 'value': 'Atlético de Madrid', 'logo': 'https://cdn.sofifa.net/teams/240/60.png'},
  {'label': 'AS Monaco', 'value': 'AS Monaco', 'logo': 'https://cdn.sofifa.net/teams/69/60.png'},
  {'label': 'Tottenham Hotspur', 'value': 'Tottenham Hotspur', 'logo': 'https://cdn.sofifa.net/teams/18/60.png'},
  {'label': 'Chelsea', 'value': 'Chelsea', 'logo': 'https://cdn.sofifa.net/teams/5/60.png'},
  {'label': 'Leicester City', 'value': 'Leicester City', 'logo': 'https://cdn.sofifa.net/teams/95/60.png'},
  {'label': 'Stade Malherbe Caen', 'value': 'Stade Malherbe Caen', 'logo': 'https://cdn.sofifa.net/teams/210/60.png'},
  {'label': 'Bayer 04 Leverkusen', 'value': 'Bayer 04 Leverkusen', 'logo': 'https://cdn.sofifa.net/teams/32/60.png'},
  {'label': 'FC Porto', 'value': 'FC Porto', 'logo': 'https://cdn.sofifa.net/teams/236/60.png'},
  {'label': 'Liverpool', 'value': 'Liverpool', 'logo': 'https://cdn.sofifa.net/teams/9/60.png'},
  {'label': 'Southampton', 'value': 'Southampton', 'logo': 'https://cdn.sofifa.net/teams/17/60.png'},
  {'label': 'Celtic', 'value': 'Celtic', 'logo': 'https://cdn.sofifa.net/teams/78/60.png'},
  {'label': 'Roma', 'value': 'Roma', 'logo': 'https://cdn.sofifa.net/teams/52/60.png'},
  {'label': 'SL Benfica', 'value': 'SL Benfica', 'logo': 'https://cdn.sofifa.net/teams/234/60.png'},
  {'label': 'Rio Ave FC', 'value': 'Rio Ave FC', 'logo': 'https://cdn.sofifa.net/teams/744/60.png'},
  {'label': 'RB Leipzig', 'value': 'RB Leipzig', 'logo': 'https://cdn.sofifa.net/teams/112172/60.png'},
  {'label': 'AC Milan', 'value': 'AC Milan', 'logo': 'https://cdn.sofifa.net/teams/47/60.png'},
  {'label': 'Inter', 'value': 'Inter', 'logo': 'https://cdn.sofifa.net/teams/44/60.png'},
  {'label': 'Everton', 'value': 'Everton', 'logo': 'https://cdn.sofifa.net/teams/7/60.png'},
  {'label': 'Sporting CP', 'value': 'Sporting CP', 'logo': 'https://cdn.sofifa.net/teams/237/60.png'},
  {'label': 'U.C. Sampdoria', 'value': 'U.C. Sampdoria', 'logo': 'https://cdn.sofifa.net/teams/1837/60.png'},
  {'label': 'Udinese Calcio', 'value': 'Udinese Calcio', 'logo': 'https://cdn.sofifa.net/teams/55/60.png'},
  {'label': 'Borussia Dortmund', 'value': 'Borussia Dortmund', 'logo': 'https://cdn.sofifa.net/teams/22/60.png'},
  {'label': 'Arsenal', 'value': 'Arsenal', 'logo': 'https://cdn.sofifa.net/teams/1/60.png'},
  {'label': 'Lazio', 'value': 'Lazio', 'logo': 'https://cdn.sofifa.net/teams/46/60.png'},
  {'label': 'Sevilla FC', 'value': 'Sevilla FC', 'logo': 'https://cdn.sofifa.net/teams/481/60.png'},
  {'label': 'FC Schalke 04', 'value': 'FC Schalke 04', 'logo': 'https://cdn.sofifa.net/teams/34/60.png'},
  {'label': 'Palermo', 'value': 'Palermo', 'logo': 'https://cdn.sofifa.net/teams/1843/60.png'},
  {'label': 'Hull City', 'value': 'Hull City', 'logo': 'https://cdn.sofifa.net/teams/1952/60.png'},
  {'label': 'Ajax', 'value': 'Ajax', 'logo': 'https://cdn.sofifa.net/teams/245/60.png'},
  {'label': 'Los Angeles FC', 'value': 'Los Angeles FC', 'logo': 'Los Angeles FC'},
  {'label': 'Villarreal CF', 'value': 'Villarreal CF', 'logo': 'https://cdn.sofifa.net/teams/483/60.png'},
  {'label': 'Valencia CF', 'value': 'Valencia CF', 'logo': 'https://cdn.sofifa.net/teams/461/60.png'},
  {'label': 'TSG Hoffenheim', 'value': 'TSG Hoffenheim', 'logo': 'https://cdn.sofifa.net/teams/10029/60.png'},
  {'label': 'Napoli', 'value': 'Napoli', 'logo': 'https://cdn.sofifa.net/teams/48/60.png'},
  {'label': 'Toronto FC', 'value': 'Toronto FC', 'logo': 'Toronto FC'},
  {'label': 'RCD Espanyol de Barcelona', 'value': 'RCD Espanyol de Barcelona', 'logo': 'https://cdn.sofifa.net/teams/452/60.png'},
  {'label': 'Athletic Club de Bilbao', 'value': 'Athletic Club de Bilbao', 'logo': 'https://cdn.sofifa.net/teams/448/60.png'},
  {'label': 'Deportivo Alavés', 'value': 'Deportivo Alavés', 'logo': 'https://cdn.sofifa.net/teams/463/60.png'},
  {'label': 'Atalanta', 'value': 'Atalanta', 'logo': 'https://cdn.sofifa.net/teams/39/60.png'},
  {'label': 'Real Sociedad', 'value': 'Real Sociedad', 'logo': 'https://cdn.sofifa.net/teams/457/60.png'},
  {'label': 'Borussia Mönchengladbach', 'value': 'Borussia Mönchengladbach', 'logo': 'https://cdn.sofifa.net/teams/23/60.png'},
  {'label': 'FC Red Bull Salzburg', 'value': 'FC Red Bull Salzburg', 'logo': 'https://cdn.sofifa.net/teams/191/60.png'},
  {'label': 'Olympique Lyonnais', 'value': 'Olympique Lyonnais', 'logo': 'https://cdn.sofifa.net/teams/66/60.png'},
  {'label': 'PSV', 'value': 'PSV', 'logo': 'https://cdn.sofifa.net/teams/247/60.png'},
  {'label': 'SV Werder Bremen', 'value': 'SV Werder Bremen', 'logo': 'https://cdn.sofifa.net/teams/38/60.png'},
  {'label': 'West Bromwich Albion', 'value': 'West Bromwich Albion', 'logo': 'https://cdn.sofifa.net/teams/109/60.png'},
  {'label': 'KRC Genk', 'value': 'KRC Genk', 'logo': 'https://cdn.sofifa.net/teams/673/60.png'},
  {'label': 'Racing Club', 'value': 'Racing Club', 'logo': 'https://cdn.sofifa.net/teams/101085/60.png'},
  {'label': 'LA Galaxy', 'value': 'LA Galaxy', 'logo': 'https://cdn.sofifa.net/teams/697/60.png'},
  {'label': 'Galatasaray SK', 'value': 'Galatasaray SK', 'logo': 'Galatasaray SK'},
  {'label': 'Newcastle United', 'value': 'Newcastle United', 'logo': 'https://cdn.sofifa.net/teams/13/60.png'},
  {'label': 'Burnley', 'value': 'Burnley', 'logo': 'https://cdn.sofifa.net/teams/1796/60.png'},
  {'label': 'RC Celta de Vigo', 'value': 'RC Celta de Vigo', 'logo': 'https://cdn.sofifa.net/teams/450/60.png'},
  {'label': 'Deportivo de La Coruña', 'value': 'Deportivo de La Coruña', 'logo': 'https://cdn.sofifa.net/teams/242/60.png'},
  {'label': 'Málaga CF', 'value': 'Málaga CF', 'logo': 'https://cdn.sofifa.net/teams/573/60.png'},
  {'label': 'Toulouse Football Club', 'value': 'Toulouse Football Club', 'logo': 'https://cdn.sofifa.net/teams/1809/60.png'},
  {'label': 'Aston Villa', 'value': 'Aston Villa', 'logo': 'Aston Villa'},
  {'label': 'Fiorentina', 'value': 'Fiorentina', 'logo': 'https://cdn.sofifa.net/teams/110374/60.png'},
  {'label': 'Getafe CF', 'value': 'Getafe CF', 'logo': 'https://cdn.sofifa.net/teams/1860/60.png'},
  {'label': 'Wolverhampton Wanderers', 'value': 'Wolverhampton Wanderers', 'logo': 'https://cdn.sofifa.net/teams/110/60.png'},
  {'label': 'Sport-Club Freiburg', 'value': 'Sport-Club Freiburg', 'logo': 'Sport-Club Freiburg'},
  {'label': 'Eintracht Frankfurt', 'value': 'Eintracht Frankfurt', 'logo': 'https://cdn.sofifa.net/teams/1824/60.png'},
  {'label': 'Hamburger SV', 'value': 'Hamburger SV', 'logo': 'https://cdn.sofifa.net/teams/28/60.png'},
  {'label': 'VfB Stuttgart', 'value': 'VfB Stuttgart', 'logo': 'https://cdn.sofifa.net/teams/36/60.png'},
  {'label': 'FC Twente', 'value': 'FC Twente', 'logo': 'https://cdn.sofifa.net/teams/1908/60.png'},
  {'label': 'OGC Nice', 'value': 'OGC Nice', 'logo': 'https://cdn.sofifa.net/teams/72/60.png'},
  {'label': 'LOSC Lille', 'value': 'LOSC Lille', 'logo': 'https://cdn.sofifa.net/teams/65/60.png'},
  {'label': 'RSC Anderlecht', 'value': 'RSC Anderlecht', 'logo': 'https://cdn.sofifa.net/teams/229/60.png'},
  {'label': 'Real Betis Balompié', 'value': 'Real Betis Balompié', 'logo': 'https://cdn.sofifa.net/teams/449/60.png'},
  {'label': 'Cagliari', 'value': 'Cagliari', 'logo': 'https://cdn.sofifa.net/teams/1842/60.png'},
  {'label': 'Zenit St. Petersburg', 'value': 'Zenit St. Petersburg', 'logo': 'https://cdn.sofifa.net/teams/100769/60.png'},
  {'label': 'Real Valladolid CF', 'value': 'Real Valladolid CF', 'logo': 'Real Valladolid CF'},
  {'label': 'Fenerbahçe SK', 'value': 'Fenerbahçe SK', 'logo': 'https://cdn.sofifa.net/teams/326/60.png'},
  {'label': 'Royal Antwerp FC', 'value': 'Royal Antwerp FC', 'logo': 'Royal Antwerp FC'},
  {'label': 'Al Ahli', 'value': 'Al Ahli', 'logo': 'https://cdn.sofifa.net/teams/112387/60.png'},
  {'label': 'Guangzhou FC', 'value': 'Guangzhou FC', 'logo': 'https://cdn.sofifa.net/teams/111839/60.png'},
  {'label': 'Fulham', 'value': 'Fulham', 'logo': 'Fulham'},
  {'label': 'Sunderland', 'value': 'Sunderland', 'logo': 'https://cdn.sofifa.net/teams/106/60.png'},
  {'label': 'U.S. Sassuolo Calcio', 'value': 'U.S. Sassuolo Calcio', 'logo': 'https://cdn.sofifa.net/teams/111974/60.png'},
  {'label': 'Olympique de Marseille', 'value': 'Olympique de Marseille', 'logo': 'https://cdn.sofifa.net/teams/219/60.png'},
  {'label': 'Genoa', 'value': 'Genoa', 'logo': 'https://cdn.sofifa.net/teams/110556/60.png'},
  {'label': 'San Lorenzo de Almagro', 'value': 'San Lorenzo de Almagro', 'logo': 'https://cdn.sofifa.net/teams/1013/60.png'},
  {'label': 'New York City FC', 'value': 'New York City FC', 'logo': 'https://cdn.sofifa.net/teams/112828/60.png'},
  {'label': 'RCD Mallorca', 'value': 'RCD Mallorca', 'logo': 'https://cdn.sofifa.net/teams/453/60.png'},
  {'label': 'Beşiktaş JK', 'value': 'Beşiktaş JK', 'logo': 'Beşiktaş JK'},
  {'label': 'AZ Alkmaar', 'value': 'AZ Alkmaar', 'logo': 'https://cdn.sofifa.net/teams/1906/60.png'},
  {'label': 'CA Osasuna', 'value': 'CA Osasuna', 'logo': 'https://cdn.sofifa.net/teams/479/60.png'},
  {'label': 'Crystal Palace', 'value': 'Crystal Palace', 'logo': 'https://cdn.sofifa.net/teams/1799/60.png'},
  {'label': 'Grêmio', 'value': 'Grêmio', 'logo': 'https://cdn.sofifa.net/teams/1629/60.png'},
  {'label': 'Palmeiras', 'value': 'Palmeiras', 'logo': 'Palmeiras'},
  {'label': 'Botafogo', 'value': 'Botafogo', 'logo': 'https://cdn.sofifa.net/teams/517/60.png'},
  {'label': 'Club Athletico Paranaense', 'value': 'Club Athletico Paranaense', 'logo': 'https://cdn.sofifa.net/teams/1039/60.png'},
  {'label': 'Derby County', 'value': 'Derby County', 'logo': 'https://cdn.sofifa.net/teams/91/60.png'},
  {'label': 'Vitesse', 'value': 'Vitesse', 'logo': 'https://cdn.sofifa.net/teams/1909/60.png'},
  {'label': 'Stade Rennais FC', 'value': 'Stade Rennais FC', 'logo': 'https://cdn.sofifa.net/teams/74/60.png'},
  {'label': 'FC Girondins de Bordeaux', 'value': 'FC Girondins de Bordeaux', 'logo': 'https://cdn.sofifa.net/teams/59/60.png'},
  {'label': 'West Ham United', 'value': 'West Ham United', 'logo': 'https://cdn.sofifa.net/teams/19/60.png'},
  {'label': 'Swansea City', 'value': 'Swansea City', 'logo': 'https://cdn.sofifa.net/teams/1960/60.png'},
  {'label': 'Torino F.C.', 'value': 'Torino F.C.', 'logo': 'https://cdn.sofifa.net/teams/54/60.png'},
  {'label': 'Al Shabab', 'value': 'Al Shabab', 'logo': 'https://cdn.sofifa.net/teams/111674/60.png'},
  {'label': 'Hannover 96', 'value': 'Hannover 96', 'logo': 'https://cdn.sofifa.net/teams/485/60.png'},
  {'label': 'Shanghai Port FC', 'value': 'Shanghai Port FC', 'logo': 'https://cdn.sofifa.net/teams/112540/60.png'},
  {'label': 'PFC CSKA Moscow', 'value': 'PFC CSKA Moscow', 'logo': 'https://cdn.sofifa.net/teams/315/60.png'},
  {'label': 'AFC Bournemouth', 'value': 'AFC Bournemouth', 'logo': 'AFC Bournemouth'},
  {'label': 'Levante Unión Deportiva', 'value': 'Levante Unión Deportiva', 'logo': 'https://cdn.sofifa.net/teams/1853/60.png'},
  {'label': 'AS Saint-Étienne', 'value': 'AS Saint-Étienne', 'logo': 'https://cdn.sofifa.net/teams/1819/60.png'},
  {'label': 'FC Nantes', 'value': 'FC Nantes', 'logo': 'https://cdn.sofifa.net/teams/71/60.png'},
  {'label': 'Girona FC', 'value': 'Girona FC', 'logo': 'https://cdn.sofifa.net/teams/110062/60.png'},
  {'label': 'Middlesbrough', 'value': 'Middlesbrough', 'logo': 'https://cdn.sofifa.net/teams/12/60.png'},
  {'label': 'SC Heerenveen', 'value': 'SC Heerenveen', 'logo': 'https://cdn.sofifa.net/teams/1913/60.png'},
  {'label': 'Real Zaragoza', 'value': 'Real Zaragoza', 'logo': 'https://cdn.sofifa.net/teams/244/60.png'},
  {'label': 'Club Atlético Independiente', 'value': 'Club Atlético Independiente', 'logo': 'https://cdn.sofifa.net/teams/110093/60.png'},
  {'label': 'Hellas Verona', 'value': 'Hellas Verona', 'logo': 'https://cdn.sofifa.net/teams/206/60.png'},
  {'label': 'Al Nassr', 'value': 'Al Nassr', 'logo': 'https://cdn.sofifa.net/teams/112139/60.png'},
  {'label': 'SC Braga', 'value': 'SC Braga', 'logo': 'https://cdn.sofifa.net/teams/1896/60.png'},
  {'label': 'Norwich City', 'value': 'Norwich City', 'logo': 'https://cdn.sofifa.net/teams/1792/60.png'},
  {'label': 'FC Paços de Ferreira', 'value': 'FC Paços de Ferreira', 'logo': 'https://cdn.sofifa.net/teams/1892/60.png'},
  {'label': 'Belenenses SAD', 'value': 'Belenenses SAD', 'logo': 'https://cdn.sofifa.net/teams/1889/60.png'},
  {'label': 'Moreirense FC', 'value': 'Moreirense FC', 'logo': 'https://cdn.sofifa.net/teams/1900/60.png'},
  {'label': 'RB Bragantino', 'value': 'RB Bragantino', 'logo': 'https://cdn.sofifa.net/teams/112472/60.png'},
  {'label': 'Santos', 'value': 'Santos', 'logo': 'https://cdn.sofifa.net/teams/1053/60.png'},
  {'label': 'Watford', 'value': 'Watford', 'logo': 'https://cdn.sofifa.net/teams/1795/60.png'},
  {'label': 'Leeds United', 'value': 'Leeds United', 'logo': 'https://cdn.sofifa.net/teams/8/60.png'},
  {'label': 'Vitória de Guimarães', 'value': 'Vitória de Guimarães', 'logo': 'https://cdn.sofifa.net/teams/1887/60.png'},
  {'label': 'Fortuna Düsseldorf', 'value': 'Fortuna Düsseldorf', 'logo': 'https://cdn.sofifa.net/teams/110636/60.png'},
  {'label': 'TSV 1860 München', 'value': 'TSV 1860 München', 'logo': 'https://cdn.sofifa.net/teams/33/60.png'},
  {'label': 'CD Leganés', 'value': 'CD Leganés', 'logo': 'https://cdn.sofifa.net/teams/100888/60.png'},
  {'label': 'Amiens SC', 'value': 'Amiens SC', 'logo': 'https://cdn.sofifa.net/teams/1816/60.png'},
  {'label': 'SK Slavia Praha', 'value': 'SK Slavia Praha', 'logo': 'https://cdn.sofifa.net/teams/266/60.png'},
  {'label': 'Dinamo Zagreb', 'value': 'Dinamo Zagreb', 'logo': 'https://cdn.sofifa.net/teams/211/60.png'},
  {'label': 'Trabzonspor', 'value': 'Trabzonspor', 'logo': 'https://cdn.sofifa.net/teams/436/60.png'},
  {'label': 'Tigres U.A.N.L.', 'value': 'Tigres U.A.N.L.', 'logo': 'https://cdn.sofifa.net/teams/1970/60.png'},
  {'label': 'Inter Miami CF', 'value': 'Inter Miami CF', 'logo': 'https://cdn.sofifa.net/teams/112893/60.png'},
  {'label': '1. FC Union Berlin', 'value': '1. FC Union Berlin', 'logo': 'https://cdn.sofifa.net/teams/1831/60.png'},
  {'label': 'Bologna', 'value': 'Bologna', 'logo': 'https://cdn.sofifa.net/teams/189/60.png'},
  {'label': 'Stoke City', 'value': 'Stoke City', 'logo': 'https://cdn.sofifa.net/teams/1806/60.png'},
  {'label': 'Shakhtar Donetsk', 'value': 'Shakhtar Donetsk', 'logo': 'https://cdn.sofifa.net/teams/101059/60.png'},
  {'label': 'F.C. København', 'value': 'F.C. København', 'logo': 'https://cdn.sofifa.net/teams/819/60.png'},
  {'label': 'Montpellier Hérault SC', 'value': 'Montpellier Hérault SC', 'logo': 'https://cdn.sofifa.net/teams/70/60.png'},
  {'label': 'Unión Deportiva Las Palmas', 'value': 'Unión Deportiva Las Palmas', 'logo': 'https://cdn.sofifa.net/teams/472/60.png'},
  {'label': 'Beijing Guoan FC', 'value': 'Beijing Guoan FC', 'logo': 'https://cdn.sofifa.net/teams/111768/60.png'},
  {'label': 'Standard de Liège', 'value': 'Standard de Liège', 'logo': 'https://cdn.sofifa.net/teams/232/60.png'},
  {'label': 'Feyenoord', 'value': 'Feyenoord', 'logo': 'https://cdn.sofifa.net/teams/246/60.png'},
  {'label': 'Clube Sport Marítimo', 'value': 'Clube Sport Marítimo', 'logo': 'https://cdn.sofifa.net/teams/1893/60.png'},
  {'label': 'Club América', 'value': 'Club América', 'logo': 'https://cdn.sofifa.net/teams/1879/60.png'},
  {'label': 'Club Atlético Lanús', 'value': 'Club Atlético Lanús', 'logo': 'https://cdn.sofifa.net/teams/110395/60.png'},
  {'label': 'Brentford', 'value': 'Brentford', 'logo': 'https://cdn.sofifa.net/teams/1925/60.png'},
  {'label': 'Olympiacos CFP', 'value': 'Olympiacos CFP', 'logo': 'https://cdn.sofifa.net/teams/280/60.png'},
  {'label': 'FC Basel 1893', 'value': 'FC Basel 1893', 'logo': 'https://cdn.sofifa.net/teams/896/60.png'},
  {'label': '1. FC Kaiserslautern', 'value': '1. FC Kaiserslautern', 'logo': 'https://cdn.sofifa.net/teams/29/60.png'},
  {'label': 'AC Monza', 'value': 'AC Monza', 'logo': 'AC Monza'},
  {'label': 'İstanbul Başakşehir FK', 'value': 'İstanbul Başakşehir FK', 'logo': 'https://cdn.sofifa.net/teams/101014/60.png'},
  {'label': 'Empoli', 'value': 'Empoli', 'logo': 'https://cdn.sofifa.net/teams/1746/60.png'},
  {'label': 'Granada CF', 'value': 'Granada CF', 'logo': 'https://cdn.sofifa.net/teams/110832/60.png'},
  {'label': 'CD Nacional', 'value': 'CD Nacional', 'logo': 'https://cdn.sofifa.net/teams/1891/60.png'},
  {'label': 'SD Huesca', 'value': 'SD Huesca', 'logo': 'https://cdn.sofifa.net/teams/110839/60.png'},
  {'label': 'Panathinaikos FC', 'value': 'Panathinaikos FC', 'logo': 'https://cdn.sofifa.net/teams/1884/60.png'},
  {'label': 'Pescara', 'value': 'Pescara', 'logo': 'https://cdn.sofifa.net/teams/200/60.png'},
  {'label': 'AC Sparta Praha', 'value': 'AC Sparta Praha', 'logo': 'https://cdn.sofifa.net/teams/267/60.png'},
  {'label': 'Sheffield United', 'value': 'Sheffield United', 'logo': 'https://cdn.sofifa.net/teams/1794/60.png'},
  {'label': 'Pachuca', 'value': 'Pachuca', 'logo': 'https://cdn.sofifa.net/teams/110147/60.png'},
  {'label': 'Angers SCO', 'value': 'Angers SCO', 'logo': 'https://cdn.sofifa.net/teams/1530/60.png'},
  {'label': 'Rosario Central', 'value': 'Rosario Central', 'logo': 'https://cdn.sofifa.net/teams/110580/60.png'},
  {'label': 'Clube Atlético Mineiro', 'value': 'Clube Atlético Mineiro', 'logo': 'https://cdn.sofifa.net/teams/1035/60.png'},
  {'label': 'Cruzeiro', 'value': 'Cruzeiro', 'logo': 'https://cdn.sofifa.net/teams/568/60.png'},
  {'label': 'Fluminense', 'value': 'Fluminense', 'logo': 'https://cdn.sofifa.net/teams/567/60.png'},
  {'label': 'Flamengo', 'value': 'Flamengo', 'logo': 'https://cdn.sofifa.net/teams/1043/60.png'},
  {'label': 'SPAL', 'value': 'SPAL', 'logo': 'https://cdn.sofifa.net/teams/112791/60.png'},
  {'label': 'Brighton & Hove Albion', 'value': 'Brighton & Hove Albion', 'logo': 'https://cdn.sofifa.net/teams/1808/60.png'},
  {'label': 'Parma', 'value': 'Parma', 'logo': 'https://cdn.sofifa.net/teams/50/60.png'},
  {'label': 'Nottingham Forest', 'value': 'Nottingham Forest', 'logo': 'Nottingham Forest'},
  {'label': 'Club Brugge KV', 'value': 'Club Brugge KV', 'logo': 'https://cdn.sofifa.net/teams/231/60.png'},
  {'label': 'Fatih Karagümrük S.K.', 'value': 'Fatih Karagümrük S.K.', 'logo': 'https://cdn.sofifa.net/teams/111117/60.png'},
  {'label': 'Boca Juniors', 'value': 'Boca Juniors', 'logo': 'https://cdn.sofifa.net/teams/1877/60.png'},
  {'label': 'River Plate', 'value': 'River Plate', 'logo': 'https://cdn.sofifa.net/teams/1876/60.png'},
  {'label': 'Seattle Sounders FC', 'value': 'Seattle Sounders FC', 'logo': 'https://cdn.sofifa.net/teams/111144/60.png'},
  {'label': 'FC Lokomotiv Moscow', 'value': 'FC Lokomotiv Moscow', 'logo': 'https://cdn.sofifa.net/teams/100765/60.png'},
  {'label': 'Bursaspor', 'value': 'Bursaspor', 'logo': 'https://cdn.sofifa.net/teams/742/60.png'},
  {'label': 'Stade de Reims', 'value': 'Stade de Reims', 'logo': 'https://cdn.sofifa.net/teams/379/60.png'},
  {'label': 'FC Augsburg', 'value': 'FC Augsburg', 'logo': 'https://cdn.sofifa.net/teams/100409/60.png'},
  {'label': 'FC Luzern', 'value': 'FC Luzern', 'logo': 'https://cdn.sofifa.net/teams/897/60.png'},
  {'label': 'Rayo Vallecano', 'value': 'Rayo Vallecano', 'logo': 'https://cdn.sofifa.net/teams/480/60.png'},
  {'label': 'CF Monterrey', 'value': 'CF Monterrey', 'logo': 'https://cdn.sofifa.net/teams/1032/60.png'},
  {'label': 'Elche CF', 'value': 'Elche CF', 'logo': 'Elche CF'},
  {'label': 'Atlanta United', 'value': 'Atlanta United', 'logo': 'https://cdn.sofifa.net/teams/112885/60.png'},
  {'label': 'Spartak Moskva', 'value': 'Spartak Moskva', 'logo': 'https://cdn.sofifa.net/teams/100767/60.png'},
  {'label': 'Stade Brestois 29', 'value': 'Stade Brestois 29', 'logo': 'https://cdn.sofifa.net/teams/378/60.png'},
  {'label': 'Unión Deportiva Almería', 'value': 'Unión Deportiva Almería', 'logo': 'Unión Deportiva Almería'},
  {'label': 'US Salernitana 1919', 'value': 'US Salernitana 1919', 'logo': 'https://cdn.sofifa.net/teams/110373/60.png'},
  {'label': 'SD Eibar', 'value': 'SD Eibar', 'logo': 'https://cdn.sofifa.net/teams/467/60.png'},
  {'label': 'Cruz Azul', 'value': 'Cruz Azul', 'logo': 'https://cdn.sofifa.net/teams/1878/60.png'},
  {'label': 'BSC Young Boys', 'value': 'BSC Young Boys', 'logo': 'https://cdn.sofifa.net/teams/900/60.png'},
  {'label': 'Internacional', 'value': 'Internacional', 'logo': 'https://cdn.sofifa.net/teams/1048/60.png'},
  {'label': '1. FSV Mainz 05', 'value': '1. FSV Mainz 05', 'logo': 'https://cdn.sofifa.net/teams/169/60.png'},
  {'label': 'Vissel Kobe', 'value': 'Vissel Kobe', 'logo': 'https://cdn.sofifa.net/teams/101146/60.png'},
  {'label': 'Al Hilal', 'value': 'Al Hilal', 'logo': 'https://cdn.sofifa.net/teams/605/60.png'},
  {'label': 'Real Oviedo', 'value': 'Real Oviedo', 'logo': 'Real Oviedo'},
  {'label': 'Rubin Kazan', 'value': 'Rubin Kazan', 'logo': 'https://cdn.sofifa.net/teams/110227/60.png'},
  {'label': 'Shanghai Shenhua FC', 'value': 'Shanghai Shenhua FC', 'logo': 'https://cdn.sofifa.net/teams/110955/60.png'},
  {'label': 'Cádiz CF', 'value': 'Cádiz CF', 'logo': 'Cádiz CF'},
  {'label': 'Real Sporting de Gijón', 'value': 'Real Sporting de Gijón', 'logo': 'https://cdn.sofifa.net/teams/459/60.png'},
  {'label': 'FC Midtjylland', 'value': 'FC Midtjylland', 'logo': 'https://cdn.sofifa.net/teams/1516/60.png'},
  {'label': 'En Avant de Guingamp', 'value': 'En Avant de Guingamp', 'logo': 'https://cdn.sofifa.net/teams/62/60.png'},
  {'label': 'ESTAC Troyes', 'value': 'ESTAC Troyes', 'logo': 'https://cdn.sofifa.net/teams/294/60.png'},
  {'label': 'Hertha BSC', 'value': 'Hertha BSC', 'logo': 'https://cdn.sofifa.net/teams/166/60.png'},
  {'label': 'FC Metz', 'value': 'FC Metz', 'logo': 'https://cdn.sofifa.net/teams/68/60.png'},
  {'label': 'RC Strasbourg Alsace', 'value': 'RC Strasbourg Alsace', 'logo': 'https://cdn.sofifa.net/teams/76/60.png'},
  {'label': 'Racing Club de Lens', 'value': 'Racing Club de Lens', 'logo': 'https://cdn.sofifa.net/teams/64/60.png'},
  {'label': 'Adana Demirspor', 'value': 'Adana Demirspor', 'logo': 'Adana Demirspor'},
  {'label': 'Vélez Sarsfield', 'value': 'Vélez Sarsfield', 'logo': 'https://cdn.sofifa.net/teams/101088/60.png'},
  {'label': '1. FC Köln', 'value': '1. FC Köln', 'logo': 'https://cdn.sofifa.net/teams/31/60.png'},
  {'label': 'Dijon FCO', 'value': 'Dijon FCO', 'logo': 'https://cdn.sofifa.net/teams/110569/60.png'},
  {'label': 'Dinamo Moscow', 'value': 'Dinamo Moscow', 'logo': 'https://cdn.sofifa.net/teams/312/60.png'},
  {'label': 'Boavista FC', 'value': 'Boavista FC', 'logo': 'https://cdn.sofifa.net/teams/1898/60.png'},
  {'label': 'KAA Gent', 'value': 'KAA Gent', 'logo': 'https://cdn.sofifa.net/teams/674/60.png'},
  {'label': 'Jiangsu FC', 'value': 'Jiangsu FC', 'logo': 'https://cdn.sofifa.net/teams/112162/60.png'},
  {'label': 'Antalyaspor', 'value': 'Antalyaspor', 'logo': 'Antalyaspor'},
  {'label': 'Club de Foot Montréal', 'value': 'Club de Foot Montréal', 'logo': 'https://cdn.sofifa.net/teams/111139/60.png'},
  {'label': 'PAOK', 'value': 'PAOK', 'logo': 'https://cdn.sofifa.net/teams/393/60.png'},
  {'label': 'Córdoba CF', 'value': 'Córdoba CF', 'logo': 'https://cdn.sofifa.net/teams/1867/60.png'},
  {'label': 'FC Krasnodar', 'value': 'FC Krasnodar', 'logo': 'https://cdn.sofifa.net/teams/112218/60.png'},
  {'label': '1. FC Nürnberg', 'value': '1. FC Nürnberg', 'logo': 'https://cdn.sofifa.net/teams/171/60.png'},
  {'label': 'FC Sion', 'value': 'FC Sion', 'logo': 'https://cdn.sofifa.net/teams/110770/60.png'},
  {'label': 'Kasimpaşa SK', 'value': 'Kasimpaşa SK', 'logo': 'https://cdn.sofifa.net/teams/111339/60.png'},
  {'label': 'Chievo Verona', 'value': 'Chievo Verona', 'logo': 'https://cdn.sofifa.net/teams/192/60.png'},
  {'label': 'Yukatel Kayserispor', 'value': 'Yukatel Kayserispor', 'logo': 'https://cdn.sofifa.net/teams/101020/60.png'},
  {'label': 'Reading', 'value': 'Reading', 'logo': 'https://cdn.sofifa.net/teams/1793/60.png'},
  {'label': 'Aytemiz Alanyaspor', 'value': 'Aytemiz Alanyaspor', 'logo': 'https://cdn.sofifa.net/teams/113142/60.png'},
  {'label': 'Club Nacional de Football', 'value': 'Club Nacional de Football', 'logo': 'https://cdn.sofifa.net/teams/111325/60.png'},
  {'label': 'Queens Park Rangers', 'value': 'Queens Park Rangers', 'logo': 'https://cdn.sofifa.net/teams/15/60.png'}
    ];
  
    export default soccer_clubs;