const nba_clubs = [
    {'label': 'Atlanta Hawks', 'value': 'Atlanta Hawks'},
{'label': 'Brooklyn Nets', 'value': 'Brooklyn Nets'},
{'label': 'Boston Celtics', 'value': 'Boston Celtics'},
{'label': 'Charlotte Hornets', 'value': 'Charlotte Hornets'},
{'label': 'Chicago Bulls', 'value': 'Chicago Bulls'},
{'label': 'Cleveland Cavailers', 'value': 'Cleveland Cavailers'},
{'label': 'Dallas Mavericks', 'value': 'Dallas Mavericks'},
{'label': 'Denver Nuggets', 'value': 'Denver Nuggets'},
{'label': 'Detroit Pistons', 'value': 'Detroit Pistons'},
{'label': 'Golden State Warriors', 'value': 'Golden State Warriors'},
{'label': 'Houston Rockets', 'value': 'Houston Rockets'},
{'label': 'Indiana Pacers', 'value': 'Indiana Pacers'},
{'label': 'Los Angeles Clippers', 'value': 'Los Angeles Clippers'},
{'label': 'Los Angeles Lakers', 'value': 'Los Angeles Lakers'},
{'label': 'Memphis Grizzlies', 'value': 'Memphis Grizzlies'},
{'label': 'Miami Heat', 'value': 'Miami Heat'},
{'label': 'Milwaukee Bucks', 'value': 'Milwaukee Bucks'},
{'label': 'Minnesota Timberwolves', 'value': 'Minnesota Timberwolves'},
{'label': 'New Orleans Pelicans', 'value': 'New Orleans Pelicans'},
{'label': 'New York Knicks', 'value': 'New York Knicks'},
{'label': 'Oklahoma City Thunder', 'value': 'Oklahoma City Thunder'},
{'label': 'Orlando Magic', 'value': 'Orlando Magic'},
{'label': 'Philadelphia 76ers', 'value': 'Philadelphia 76ers'},
{'label': 'Phoenix Suns', 'value': 'Phoenix Suns'},
{'label': 'Portland Trail Blazers', 'value': 'Portland Trail Blazers'},
{'label': 'Sacremento Kings', 'value': 'Sacremento Kings'},
{'label': 'San Antonio Spurs', 'value': 'San Antonio Spurs'},
{'label': 'Toronto Raptors', 'value': 'Toronto Raptors'},
{'label': 'Utah Jazz', 'value': 'Utah Jazz'},
{'label': 'Washington Wizards', 'value': 'Washington Wizards'},
];

export default nba_clubs;